CREATE VIEW ENVDAYAVG AS 
SELECT 
    FARM_ID,
    DATE,
    ROUND(AVG(TEMP),2)       AS TEMP,
    ROUND(AVG(HUMID),2)      AS HUMID,
    ROUND(AVG(DEWPOINT),2)   AS DEWPOINT,
    ROUND(AVG(FLOW),2)       AS FLOW,
    ROUND(AVG(RAIN_GAUGE),2) AS RAIN_GAUGE,
    ROUND(AVG(ACTINO),2)     AS ACTINO,
    ROUND(AVG(WINDDIR),2)    AS WINDDIR,
    ROUND(AVG(WINDSPEED),2)  AS WINDSPEED,
    ROUND(AVG(VOLTAGE),2)    AS VOLTAGE,
    ROUND(AVG(CO2),2)        AS CO2,
    ROUND(AVG(EC),2)         AS EC,
    ROUND(AVG(SOIL_HUM),2)   AS SOIL_HUM,
    ROUND(AVG(SMOKE),2)      AS SMOKE,
    ROUND(AVG(GAS),2)        AS GAS,
    ROUND(AVG(BRIGHT),2)     AS BRIGHT,
    ROUND(AVG(E_CURRENT),2)  AS E_CURRENT
FROM ENVINFOTABLE GROUP BY FARM_ID, DATE;



CREATE VIEW ENVHOURAVG AS 
SELECT 
    FARM_ID,
    DATE,
    LEFT(TIME, 2)            AS TIME,
    ROUND(AVG(TEMP),2)       AS TEMP,
    ROUND(AVG(HUMID),2)      AS HUMID,
    ROUND(AVG(DEWPOINT),2)   AS DEWPOINT,
    ROUND(AVG(FLOW),2)       AS FLOW,
    ROUND(AVG(RAIN_GAUGE),2) AS RAIN_GAUGE,
    ROUND(AVG(ACTINO),2)     AS ACTINO,
    ROUND(AVG(WINDDIR),2)    AS WINDDIR,
    ROUND(AVG(WINDSPEED),2)  AS WINDSPEED,
    ROUND(AVG(VOLTAGE),2)    AS VOLTAGE,
    ROUND(AVG(CO2),2)        AS CO2,
    ROUND(AVG(EC),2)         AS EC,
    ROUND(AVG(SOIL_HUM),2)   AS SOIL_HUM,
    ROUND(AVG(SMOKE),2)      AS SMOKE,
    ROUND(AVG(GAS),2)        AS GAS,
    ROUND(AVG(BRIGHT),2)     AS BRIGHT,
    ROUND(AVG(E_CURRENT),2)  AS E_CURRENT
FROM ENVINFOTABLE GROUP BY FARM_ID, DATE, LEFT(TIME, 2);



CREATE VIEW ENVMONTHAVG AS 
SELECT 
    FARM_ID,
    RIGHT(LEFT(DATE, 6), 2)   AS DATE,
    ROUND(AVG(TEMP),2)       AS TEMP,
    ROUND(AVG(HUMID),2)      AS HUMID,
    ROUND(AVG(DEWPOINT),2)   AS DEWPOINT,
    ROUND(AVG(FLOW),2)       AS FLOW,
    ROUND(AVG(RAIN_GAUGE),2) AS RAIN_GAUGE,
    ROUND(AVG(ACTINO),2)     AS ACTINO,
    ROUND(AVG(WINDDIR),2)    AS WINDDIR,
    ROUND(AVG(WINDSPEED),2)  AS WINDSPEED,
    ROUND(AVG(VOLTAGE),2)    AS VOLTAGE,
    ROUND(AVG(CO2),2)        AS CO2,
    ROUND(AVG(EC),2)         AS EC,
    ROUND(AVG(SOIL_HUM),2)   AS SOIL_HUM,
    ROUND(AVG(SMOKE),2)      AS SMOKE,
    ROUND(AVG(GAS),2)        AS GAS,
    ROUND(AVG(BRIGHT),2)     AS BRIGHT,
    ROUND(AVG(E_CURRENT),2)  AS E_CURRENT
FROM ENVINFOTABLE GROUP BY FARM_ID, RIGHT(LEFT(DATE, 6), 2);



CREATE VIEW ENVDAYMAX AS 
SELECT 
    FARM_ID,
    DATE,
    ROUND(MAX(TEMP),2)       AS TEMP,
    ROUND(MAX(HUMID),2)      AS HUMID,
    ROUND(MAX(DEWPOINT),2)   AS DEWPOINT,
    ROUND(MAX(FLOW),2)       AS FLOW,
    ROUND(MAX(RAIN_GAUGE),2) AS RAIN_GAUGE,
    ROUND(MAX(ACTINO),2)     AS ACTINO,
    ROUND(MAX(WINDDIR),2)    AS WINDDIR,
    ROUND(MAX(WINDSPEED),2)  AS WINDSPEED,
    ROUND(MAX(VOLTAGE),2)    AS VOLTAGE,
    ROUND(MAX(CO2),2)        AS CO2,
    ROUND(MAX(EC),2)         AS EC,
    ROUND(MAX(SOIL_HUM),2)   AS SOIL_HUM,
    ROUND(MAX(SMOKE),2)      AS SMOKE,
    ROUND(MAX(GAS),2)        AS GAS,
    ROUND(MAX(BRIGHT),2)     AS BRIGHT,
    ROUND(MAX(E_CURRENT),2)  AS E_CURRENT
FROM ENVINFOTABLE GROUP BY FARM_ID, DATE;



CREATE VIEW ENVDAYSTS AS 
SELECT 
    FARM_ID,
    DATE,
    ROUND(MIN(TEMP),2)       AS MIN_TEMP,
    ROUND(MIN(HUMID),2)      AS MIN_HUMID,
    ROUND(MIN(DEWPOINT),2)   AS MIN_DEWPOINT,
    ROUND(MIN(FLOW),2)       AS MIN_FLOW,
    ROUND(MIN(RAIN_GAUGE),2) AS MIN_RAIN_GAUGE,
    ROUND(MIN(ACTINO),2)     AS MIN_ACTINO,
    ROUND(MIN(WINDDIR),2)    AS MIN_WINDDIR,
    ROUND(MIN(WINDSPEED),2)  AS MIN_WINDSPEED,
    ROUND(MIN(VOLTAGE),2)    AS MIN_VOLTAGE,
    ROUND(MIN(CO2),2)        AS MIN_CO2,
    ROUND(MIN(EC),2)         AS MIN_EC,
    ROUND(MIN(SOIL_HUM),2)   AS MIN_SOIL_HUM,
    ROUND(MIN(SMOKE),2)      AS MIN_SMOKE,
    ROUND(MIN(GAS),2)        AS MIN_GAS,
    ROUND(MIN(BRIGHT),2)     AS MIN_BRIGHT,
    ROUND(MIN(E_CURRENT),2)  AS MIN_E_CURRENT,
    ROUND(MAX(TEMP),2)       AS MAX_TEMP,
    ROUND(MAX(HUMID),2)      AS MAX_HUMID,
    ROUND(MAX(DEWPOINT),2)   AS MAX_DEWPOINT,
    ROUND(MAX(FLOW),2)       AS MAX_FLOW,
    ROUND(MAX(RAIN_GAUGE),2) AS MAX_RAIN_GAUGE,
    ROUND(MAX(ACTINO),2)     AS MAX_ACTINO,
    ROUND(MAX(WINDDIR),2)    AS MAX_WINDDIR,
    ROUND(MAX(WINDSPEED),2)  AS MAX_WINDSPEED,
    ROUND(MAX(VOLTAGE),2)    AS MAX_VOLTAGE,
    ROUND(MAX(CO2),2)        AS MAX_CO2,
    ROUND(MAX(EC),2)         AS MAX_EC,
    ROUND(MAX(SOIL_HUM),2)   AS MAX_SOIL_HUM,
    ROUND(MAX(SMOKE),2)      AS MAX_SMOKE,
    ROUND(MAX(GAS),2)        AS MAX_GAS,
    ROUND(MAX(BRIGHT),2)     AS MAX_BRIGHT,
    ROUND(MAX(E_CURRENT),2)  AS MAX_E_CURRENT,
    ROUND(AVG(TEMP),2)       AS AVG_TEMP,
    ROUND(AVG(HUMID),2)      AS AVG_HUMID,
    ROUND(AVG(DEWPOINT),2)   AS AVG_DEWPOINT,
    ROUND(AVG(FLOW),2)       AS AVG_FLOW,
    ROUND(AVG(RAIN_GAUGE),2) AS AVG_RAIN_GAUGE,
    ROUND(AVG(ACTINO),2)     AS AVG_ACTINO,
    ROUND(AVG(WINDDIR),2)    AS AVG_WINDDIR,
    ROUND(AVG(WINDSPEED),2)  AS AVG_WINDSPEED,
    ROUND(AVG(VOLTAGE),2)    AS AVG_VOLTAGE,
    ROUND(AVG(CO2),2)        AS AVG_CO2,
    ROUND(AVG(EC),2)         AS AVG_EC,
    ROUND(AVG(SOIL_HUM),2)   AS AVG_SOIL_HUM,
    ROUND(AVG(SMOKE),2)      AS AVG_SMOKE,
    ROUND(AVG(GAS),2)        AS AVG_GAS,
    ROUND(AVG(BRIGHT),2)     AS AVG_BRIGHT,
    ROUND(AVG(E_CURRENT),2)  AS AVG_E_CURRENT
FROM ENVINFOTABLE GROUP BY FARM_ID, DATE;



