CREATE VIEW ENVDAYAVG AS 
SELECT 
    FARM_ID,
    DATE,
    AVG(TEMP)       AS TEMP,
    AVG(HUMID)      AS HUMID,
    AVG(DEWPOINT)   AS DEWPOINT,
    AVG(FLOW)       AS FLOW,
    AVG(RAIN_GAUGE) AS RAIN_GAUGE,
    AVG(ACTINO)     AS ACTINO,
    AVG(WINDDIR)    AS WINDDIR,
    AVG(WINDSPEED)  AS WINDSPEED,
    AVG(VOLTAGE)    AS VOLTAGE,
    AVG(CO2)        AS CO2,
    AVG(EC)         AS EC,
    AVG(SOIL_HUM)   AS SOIL_HUM,
    AVG(SMOKE)      AS SMOKE,
    AVG(GAS)        AS GAS,
    AVG(BRIGHT)     AS BRIGHT,
    AVG(E_CURRENT)  AS E_CURRENT
FROM ENVINFOTABLE GROUP BY DATE;

